### ISSUE TITLE
Version 2.0.1 failing with Flutter 3.24

### ISSUE THREAD

**Issue by borgoat** [flutter-form-builder-ecosystem/form_builder_phone_field#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

2.0.1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-CH)
    • Flutter version 3.24.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.9/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/borgoat/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/borgoat/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/borgoat/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
    • IntelliJ at /Users/borgoat/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.20629

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • 🤙 (mobile)                     • 00008110-000E0D9C1132401E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.84

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

#### **`pubspec.yaml`**
```yaml
dependencies:
  flutter_form_builder: ^9.1.1
  form_builder_phone_field: ^2.0.1
```

#### **`pubspec.lock`**
```yaml
packages:
  form_builder_phone_field:
    dependency: "direct main"
    description:
      name: form_builder_phone_field
      sha256: b959f560ad94f4ecbc48830d5485b187aa02d87a02a97cdb874bc6ddd87d0dcb
      url: "https://pub.dev"
    source: hosted
    version: "2.0.1"
```

</details>

### Current Behavior

I'm getting an error when building:

```
Could not build the precompiled application for the device.
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/country_pickers-2.0.0/lib/utils/my_alert_dialog.dart:107:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
```

### Expected Behavior

I can build by overriding the dependency to point to branch `main` of this repo:

#### **`pubspec.yaml`**
```
dependency_overrides:
  form_builder_phone_field:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field.git
      ref: main
```

### Steps To Reproduce

1. Use Flutter 3.24
2. Add dependency to `form_builder_phone_field: 2.0.1`
3. Build

### Aditional information

I wonder if there's something wrong with tags and actual releases on pub.dev:

* 2.0.0 and 2.0.1 are from a couple of weeks ago here: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/releases
* But on pub.dev, it says they're older than a year: https://pub.dev/packages/form_builder_phone_field/versions
